<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>TaskListLocations</RootNamespace>
    <Nullable>disable</Nullable>
    <Authors>Passass</Authors>
    <Copyright>Copyright © 2026 Passass</Copyright>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Configurations>Debug;Release;Package</Configurations>
    <Version>$(AssemblyVersion)</Version>
	<TarkovDir>E:\EscapeFromTarkov\</TarkovDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Package|AnyCPU'">
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Package\**" />
    <EmbeddedResource Remove="Package\**" />
    <None Remove="Package\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony, Version=2.9.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TarkovDir)BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>$(TarkovDir)EscapeFromTarkov_Data\Managed\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="spt-common">
      <HintPath>$(TarkovDir)BepInEx\plugins\spt\spt-common.dll</HintPath>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>$(TarkovDir)BepInEx\plugins\spt\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(TarkovDir)EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(TarkovDir)EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(TarkovDir)BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(TarkovDir)EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(TarkovDir)EscapeFromTarkov_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(TarkovDir)EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(TarkovDir)EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TarkovDir)EscapeFromTarkov_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
	<Reference Include="spt-custom">
      <HintPath>$(TarkovDir)BepInEx\plugins\spt\spt-custom.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TarkovDir)EscapeFromTarkov_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
